### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by ghost** [leojrfs/miband2#1]
Many thanks, exactly what i was searching for. I want to read heart rate values by myself but unfortunately it doesn't work for me:

sudo python
miband2_auth.py "MAC"
Connecting to MAC
Traceback (most recent call last):
File "miband2_auth.py", line 136, in <mod
ule>
main()
File "miband2_auth.py", line 116, in main
band = MiBand2(arg.host)
File "miband2_auth.py", line 17, in __ini
t__
Peripheral.__init__(self, addr, addrTyp
e=ADDR_TYPE_RANDOM)
File "/usr/local/lib/python2.7/dist-packa
ges/bluepy-1.1.4-py2.7.egg/bluepy/btle.py",
line 353, in __init__
self._connect(deviceAddr, addrType, ifa
ce)
File "/usr/local/lib/python2.7/dist-packa
ges/bluepy-1.1.4-py2.7.egg/bluepy/btle.py",
line 402, in _connect
"Failed to connect to peripheral %s, ad
dr type: %s" % (addr, addrType))
bluepy.btle.BTLEException: Failed to connec
t to peripheral MAC, addr typ
e: random

Any hints? I tried all security levels and address types. Thank you.

**Comment by leojrfs** [comment]
Just to clarify, you arent really using “MAC” string are you?

**Comment by leojrfs** [comment]
If you are really using the correct mac address, you should make sure that the band isnt connected to the phone (try unpairing, or even turning off bluetooth just o make sure)

**Comment by ghost** [comment]
I am using correct MAC address returned by 'hcitool lescan'. I will recheck with gatttool next.

**Comment by leojrfs** [comment]
The device is probably connected to the phone still. Yes, try to to connect to it using gatttool or bluetoothctl

**Comment by ghost** [comment]
Great, it's working now

Connecting to MAC
Connected
Enabling Auth Service notifications status...
Requesting random number...
Sending encrypted random number
Authenticated!
Sending message notification...
Sending phone notification...
Turning off notifications...
Disconnecting...
