### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ghost** [leojrfs/miband2#2]
As i read your blog https://leojrfs.github.io/writing/miband2-part1-auth/ do you have further plans with this piece of python code or do you just play and experiment with BLE and Miband2?

**Comment by leojrfs** [comment]
Was thinking about doing a part2 blog post to get data. HR, activity, etc... and further complete the code, just a short script, because I was using it in a project, but not anymore.

Anyways, if there are more interested in contributing to create a more complete tool, I am up for it.

**Comment by ghost** [comment]
I am interested in getting the main data (steps, HR etc.) too, from command line would be cool to be flexible but so far i did not know where to start, especially translating parts of the Java code of Gadgetbridge to something i can directly try out with gatttool or with Python. There is no up to date Python code handling the MIBAND2 as far as i know.  

I saw https://github.com/peplin/pygatt which sounds interesting and https://github.com/jdesbonnet/MiBand2Tools for evaluating stuff from gadgetbridge database. 

Maybe one can start with Python and collect first data to a csv and use ncurses for visualization of the data. Some simple stuff first. I have to think about it.

**Comment by leojrfs** [comment]
After authentication you can use bluetoothctl and try stuff on the command line.
I didn't find it to be much difficult to understand gadgetbridge the miband2 support. Their Java code is quite readable. 

I tried `pygatt` but i find `bluepy`way superior, also `pygatt` is just a wrapper on top of the `gatttool` cmdline utility.

I was thinking about dumping data as text (Unix Style) as long as there is no need for constant monitoring of something.

**Comment by ghost** [comment]
People might be interested in constant monitoring sleep and HR but i would suggest to keep it simple in the beginning.

**Comment by ghost** [comment]
To get an idea how the 'translation' works, can you give a hint from where you got the handle 0x25 for notifications here? Thank you.  

`
band.writeCharacteristic(0x25, struct.pack('<b', 0x01))
`

How one can read for instance the current number of steps from the device?

p.s. Got it `char value handle: 0x0025, uuid: 00002a06-0000-1000-8000-00805f9b34fb`

**Comment by leojrfs** [comment]
Im not working with this anymore.

Theres a fork by @creotiv with extended work and more features. Check #4

https://github.com/creotiv/MiBand2
