### ISSUE TITLE
Hey man, we add some changes based on your work

### ISSUE THREAD

**Issue by creotiv** [leojrfs/miband2#4]
First of all want to say thank you for your work, it became starting point of our work.

So right now we have updated protocol here https://github.com/creotiv/MiBand2 you can use it for your case if you want. We add:
- some additional info parsing: time, battery, serial, revisions.
- added realtime parsing for heart monitor(both measures and raw data) and for gyroscope raw data

**Comment by leojrfs** [comment]
Great! im going to leave it on the Readme to redirect to your repo since im not working on this anymore.
